In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_excel("../artifacts/supermarket_inventory_data2.xlsx")

In [3]:
sales = data.drop(['DeliveryTimeDays', 'DeliveryStatus'], axis=1)

In [5]:
sales.isnull().sum()

Date                 0
ProductID            0
ProductName          0
Category             0
Supplier             0
UnitPrice            0
StockQuantity        0
StockValue           0
ReorderLevel         0
ReorderQuantity      0
UnitsSold            0
SalesValue           0
LastSoldDate       151
LastRestockDate      0
NextRestockDate      0
dtype: int64

In [6]:
sales.dropna(subset=['LastSoldDate'], inplace=True)

In [7]:
sales.isnull().sum()

Date               0
ProductID          0
ProductName        0
Category           0
Supplier           0
UnitPrice          0
StockQuantity      0
StockValue         0
ReorderLevel       0
ReorderQuantity    0
UnitsSold          0
SalesValue         0
LastSoldDate       0
LastRestockDate    0
NextRestockDate    0
dtype: int64

In [8]:
y = sales['StockQuantity']
y

0        55
1       189
2       130
3        96
4       109
       ...
9995     50
9996     14
9997     79
9998    160
9999    129
Name: StockQuantity, Length: 9849, dtype: int64

In [9]:
X = sales.drop('StockQuantity', axis=1)
X

,Date,ProductID,ProductName,Category,Supplier,UnitPrice,StockValue,ReorderLevel,ReorderQuantity,UnitsSold,SalesValue,LastSoldDate,LastRestockDate,NextRestockDate
0,2024-03-09,a8cf4d43-f0fc-43b0-a6f6-74f30b13b5db,Juice,Beverages,Mcdowell Group,89.94,4946.70,34,47,4,359.76,2024-04-18,2024-06-10,2024-07-04
1,2024-03-12,9740c875-68c3-4909-8f88-8069bf5ab35b,Bread,Bakery,"Nunez, Miles and Palmer",9.82,1855.98,12,22,5,49.10,2024-06-12,2024-06-22,2024-06-29
2,2024-01-23,98434ac8-5c4d-42c7-a26d-48c35f4849c9,Granola Bars,Snacks,Johnson-Vincent,48.66,6325.80,29,24,19,924.54,2024-04-29,2024-05-19,2024-05-28
3,2024-03-27,438b285c-839f-413a-9d5d-6dc8d24a7a8d,Cream,Dairy,Key-Shah,54.87,5267.52,27,20,65,3566.55,2024-05-31,2024-02-24,2024-02-27
4,2024-01-21,45dd839a-911a-4c87-8217-5052b6a2c7aa,Potato,Produce,Jones Ltd,49.69,5416.21,9,66,11,546.59,2024-03-01,2024-05-25,2024-06-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024-03-30,4f64216a-538c-449c-9ace-f63146dd60e5,Trash Bags,Cleaning Supplies,Knight-Price,91.16,4558.00,14,25,3,273.48,2024-02-19,2024-03-26,2024-04-16
9996,2024-01-22,bc9a8e8a-dd70-49be-a9ab-1bead5777abd,Milk,Dairy,"Hamilton, Fields and Nguyen",10.14,141.96,39,71,1,10.14,2024-01-04,2024-02-05,2024-02-19
9997,2024-01-23,1d0a072a-09af-4497-8061-89be604dceeb,Fish,Meat,Hines-Hamilton,58.40,4613.60,28,42,26,1518.40,2024-01-07,2024-01-28,2024-02-04
9998,2024-05-24,74563795-7be6-40c2-9f43-56be3bc515c6,Ice Cream,Frozen,"Boyer, Riley and Gonzalez",25.55,4088.00,10,66,15,383.25,2024-03-01,2024-03-13,2024-04-08
9999,2024-04-09,bb8f23c9-1680-46d0-ac28-5cec04986aa3,Fish,Meat,Williams Ltd,44.92,5794.68,24,64,44,1976.48,2024-02-18,2024-04-22,2024-04-24

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 100)

In [11]:
X_train

,Date,ProductID,ProductName,Category,Supplier,UnitPrice,StockValue,ReorderLevel,ReorderQuantity,UnitsSold,SalesValue,LastSoldDate,LastRestockDate,NextRestockDate
4429,2024-04-04,e35707a5-7890-4e07-a902-9cf0be06fc5f,Potato,Produce,"Watson, Waters and Leblanc",32.20,4153.80,45,32,33,1062.60,2024-05-05,2024-03-21,2024-03-31
2580,2024-01-12,51d3570c-e363-4d0c-8388-723c6cfa4f4f,Beef,Meat,"Martin, Wright and Estes",63.05,7376.85,11,24,30,1891.50,2024-02-19,2024-05-14,2024-06-06
6312,2024-02-21,9c8ed7fb-429f-4bd5-9747-71f07d913abb,Water,Beverages,Ayala-Burns,39.48,1658.16,21,94,33,1302.84,2024-04-02,2024-01-14,2024-01-29
1123,2024-01-09,39bfd298-774a-4ffd-95f5-50d27dcfbdb4,Lamb,Meat,White-Vasquez,64.46,4705.58,19,73,23,1482.58,2024-03-01,2024-04-07,2024-04-24
8578,2024-03-19,9372d399-0f76-4e98-ab36-7d88e65aec98,Beef,Meat,"Harper, Sparks and Miller",59.78,10760.40,21,42,172,10282.16,2024-01-27,2024-06-19,2024-06-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,2024-02-15,c475dc97-7496-4386-8695-9ac4d8deaea4,Frozen Vegetables,Frozen,Brady-Howell,69.95,1958.60,15,87,21,1468.95,2024-04-08,2024-02-27,2024-03-17
81,2024-06-26,8f60e825-9a74-4f9a-bb97-d92cc0ff2a22,Pizza,Frozen,Cortez-Patton,12.01,348.29,44,84,27,324.27,2024-05-11,2024-02-08,2024-03-02
8171,2024-03-29,d3b079bc-341a-42b5-9c08-1f300c3db7a1,Chicken Nuggets,Frozen,Oneill-Wallace,97.61,7125.53,6,35,15,1464.15,2024-02-14,2024-03-22,2024-04-21
7047,2024-01-18,a9e278a5-4e44-49f1-b8d3-be8ef410ceb5,Juice,Beverages,Allen PLC,65.15,1368.15,24,46,19,1237.85,2024-06-10,2024-01-03,2024-01-23
5735,2024-04-19,bea0067f-567a-41a6-87c1-ec09b08a372e,Tea,Beverages,"Morris, Gates and Hutchinson",96.46,2797.34,46,94,13,1253.98,2024-01-25,2024-03-01,2024-03-27

In [12]:
X_test

,Date,ProductID,ProductName,Category,Supplier,UnitPrice,StockValue,ReorderLevel,ReorderQuantity,UnitsSold,SalesValue,LastSoldDate,LastRestockDate,NextRestockDate
2492,2024-03-22,d9d7dad9-fb8d-4c18-b895-ce75ed87a73f,Shampoo,Health & Beauty,Brown-Henderson,76.15,13173.95,24,25,166,12640.90,2024-02-12,2024-03-31,2024-04-20
5300,2024-05-03,4b7dcd6c-3020-40b7-83c9-ff0a22d67c3b,Cookies,Snacks,Moss Inc,11.94,238.80,19,53,1,11.94,2024-04-23,2024-06-11,2024-06-22
8046,2024-04-03,1da8fee8-4601-4a85-8f0b-9f1526e9ee4d,Bread,Bakery,"Burton, Powell and Pace",83.57,3844.22,10,52,11,919.27,2024-05-17,2024-06-21,2024-07-06
292,2024-01-20,05b83fef-1e95-46c8-9170-1dee150885c3,Lamb,Meat,Bell-Grant,93.84,15858.96,25,41,67,6287.28,2024-02-21,2024-02-27,2024-03-19
2050,2024-06-04,7c07fc38-b3b5-4998-bc49-64bd2fc1ea06,Bread,Bakery,Powell-Mcdonald,6.81,1273.47,7,94,101,687.81,2024-02-24,2024-02-13,2024-03-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,2024-03-15,c986752a-d67d-431b-b329-9e12e4df61c7,Deodorant,Health & Beauty,Maddox-Jackson,23.66,1041.04,46,21,39,922.74,2024-05-22,2024-06-24,2024-07-21
2525,2024-04-13,371e8e87-7ed9-429c-949d-67341b46c261,Fish,Meat,Monroe-Garcia,69.12,6082.56,24,58,86,5944.32,2024-03-07,2024-05-31,2024-06-22
3714,2024-01-24,20dceaa9-7b84-4a57-b933-ee4a8344ff82,Ice Cream,Frozen,Howard-Ross,94.97,10731.61,33,82,49,4653.53,2024-06-12,2024-01-19,2024-01-29
8052,2024-03-27,a13ca530-b790-4dfa-a464-f55662881a88,Shampoo,Health & Beauty,Griffin Inc,10.21,439.03,13,60,36,367.56,2024-04-13,2024-01-13,2024-01-17
7698,2024-04-01,66a52897-1c5f-416c-afba-5da07e3ba52a,Bagel,Bakery,Coleman-Johnson,15.50,2728.00,33,48,14,217.00,2024-01-21,2024-01-15,2024-02-02

# Training Model

## Linear Regression

In [15]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

ValueError: could not convert string to float: '2024-04-04'